/* demos/music/music_player.c
 *
 * MIT License
 *
 * Copyright(c) 2023-present All contributors of SGL
 * Document reference link: https://sgl-docs.readthedocs.io
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <sgl.h>
#include <sgl_font.h>
#include <sgl_anim.h>
#include <stdio.h>
#include <stdlib.h>

/**
 * Music player UI demo (light theme, adaptive to screen size).
 *
 * Layout follows demos/music/layout.html, scaled to fill the screen:
 *   - background: #eef0f6 full screen
 *   - 3 decorative background blobs (light circles, alpha-blended)
 *   - left column: title / artist / meta, 4 action icons, 5 control buttons,
 *     progress bar with dot knob + time label
 *   - right column: circular cover with white border + music icon,
 *     spectrum below
 *   - bottom center: "ALL TRACKS" caption with small underline
 *   - swipe up to reveal the track list sheet (dark gradient panel)
 *   - swipe down to hide the track list sheet
 *
 * Icons are FontAwesome glyphs converted to sgl/source/fonts/sgl_icon_music20.c
 * via sgl_font_conv_cli (20px, bpp=4).
 */

/* generated by sgl_font_conv_cli from fonts/FontAwesome.otf */
extern const sgl_font_t sgl_icon_music20;

/* FontAwesome icon codepoints (UTF-8 encoded) */
#define ICON_MUSIC       "\xf0\x8f\x80\x81"   /* U+F001 music           */
#define ICON_HEART       "\xf0\x8f\x80\x84"   /* U+F004 heart           */
#define ICON_DOWNLOAD    "\xf0\x8f\x80\x99"   /* U+F019 download        */
#define ICON_REPEAT      "\xf0\x8f\x80\x9e"   /* U+F01E repeat          */
#define ICON_PREV        "\xef\x81\x88"       /* U+F048 backward-step   */
#define ICON_PLAY        "\xef\x81\x8b"       /* U+F04B play            */
#define ICON_PAUSE       "\xef\x81\x8c"       /* U+F04C pause           */
#define ICON_NEXT        "\xef\x81\x91"       /* U+F051 forward-step    */
#define ICON_SHUFFLE     "\xef\x81\xb4"       /* U+F074 shuffle         */
#define ICON_CHART       "\xef\x82\x80"       /* U+F080 chart-bar       */
#define ICON_ELLIPSIS    "\xef\x85\x81"       /* U+F141 ellipsis-h      */

/* screen geometry - use SGL screen size macros */
#define SCR_W            SGL_SCREEN_WIDTH
#define SCR_H            SGL_SCREEN_HEIGHT

/* layout margins - proportional to screen size */
#define MARGIN_X         (SCR_W / 13)      /* ~60 for 800px width */
#define MARGIN_TOP       (SCR_H / 10)      /* ~48 for 480px height */
#define MARGIN_BOT       (SCR_H / 10)      /* ~48 for 480px height */

/* left column - takes about half of screen width */
#define LEFT_X           MARGIN_X
#define LEFT_W           (SCR_W / 2 - MARGIN_X)
#define TITLE_Y          MARGIN_TOP
#define ARTIST_Y         (TITLE_Y + SCR_H / 12)
#define META_Y           (ARTIST_Y + SCR_H / 17)
#define ACTIONS_Y        (META_Y + SCR_H / 10)
#define CONTROLS_Y       (ACTIONS_Y + SCR_H / 8)
#define PROGRESS_Y       (SCR_H - MARGIN_BOT - SCR_H / 24)

/* right column */
#define RIGHT_X          (SCR_W / 2 + MARGIN_X / 2)
#define RIGHT_W          (SCR_W / 2 - MARGIN_X)
#define COVER_SIZE       (SCR_H / 2 - 20)  /* ~220 for 480px height */
#define SPEC_W           RIGHT_W
#define SPEC_H           (SCR_H / 8)
#define SPEC_BARS        46

/* progress */
#define PROG_H           6
#define PROG_DOT         12
#define SONG_LEN_SEC     214   /* 3:34 */

/* sheet (track list panel) */
#define SHEET_H          (SCR_H - SCR_H / 8)   /* leave top margin */
#define SHEET_Y_CLOSE    SCR_H                 /* fully below screen */
#define SHEET_Y_OPEN     (SCR_H / 8)           /* top edge when open */
#define SHEET_RADIUS     20
#define SHEET_HANDLE_W   50
#define SHEET_HANDLE_H   5
#define TRACK_ITEM_H     64
#define TRACK_NUM        20

/* sheet animation duration (ms) */
#define SHEET_ANIM_MS    300

/* color palette (light theme, from layout.html) */
#define COL_BG           sgl_rgb(238, 240, 246)   /* #eef0f6 */
#define COL_TITLE        sgl_rgb(59, 63, 82)      /* #3b3f52 */
#define COL_ARTIST       sgl_rgb(74, 78, 99)      /* #4a4e63 */
#define COL_META         sgl_rgb(138, 143, 165)   /* #8a8fa5 */
#define COL_ICON         sgl_rgb(91, 96, 118)     /* #5b6076 */
#define COL_ICON_CTRL    sgl_rgb(106, 111, 134)   /* #6a6f86 */
#define COL_ACCENT       sgl_rgb(122, 104, 245)   /* #7a68f5 */
#define COL_ACCENT_LIGHT sgl_rgb(157, 141, 255)   /* #9d8dff */
#define COL_TRACK        sgl_rgb(226, 228, 238)   /* #e2e4ee */
#define COL_BLOB1        sgl_rgb(223, 228, 255)   /* #dfe4ff */
#define COL_BLOB2        sgl_rgb(230, 233, 251)   /* #e6e9fb */
#define COL_BLOB3        sgl_rgb(215, 240, 238)   /* #d7f0ee */
#define COL_COVER_DARK   sgl_rgb(35, 32, 58)      /* #23203a */
#define COL_SPEC_BOT     sgl_rgb(138, 123, 248)   /* #8a7bf8 */
#define COL_ALLTRACKS    sgl_rgb(125, 129, 160)   /* #7d81a0 */
#define COL_ALLTRACKS_LN sgl_rgb(201, 196, 245)   /* #c9c4f5 */

/* sheet colors (dark gradient) */
#define COL_SHEET_TOP    sgl_rgb(70, 65, 101)     /* #464165 */
#define COL_SHEET_BOT    sgl_rgb(55, 50, 79)      /* #37324f */
#define COL_HANDLE       sgl_rgb(255, 255, 255)   /* rgba(255,255,255,.28) */
#define COL_TRACK_NAME   sgl_rgb(217, 218, 234)   /* #d9daea */
#define COL_TRACK_ARTIST sgl_rgb(143, 144, 171)   /* #8f90ab */
#define COL_TRACK_DUR    sgl_rgb(167, 168, 194)   /* #a7a8c2 */
#define COL_TRACK_ACT_N  sgl_rgb(255, 255, 255)   /* active name */
#define COL_TRACK_ACT_A  sgl_rgb(179, 174, 240)   /* active artist */
#define COL_TRACK_BTN    sgl_rgb(236, 238, 248)   /* #eceef8 */

/* widgets */
static sgl_obj_t *progress_bar;
static sgl_obj_t *progress_dot;
static sgl_obj_t *time_label;
static sgl_obj_t *play_btn;
static sgl_obj_t *spectrum;
static sgl_obj_t *sheet;
static sgl_obj_t *sheet_handle;
static sgl_obj_t *track_viewlist;

/* player state */
static bool     playing = true;
static uint32_t elapsed_sec;
static int16_t  spec_phase;
static int16_t  sheet_y;                   /* current sheet top y, initialized in create */
static bool     sheet_open = false;
static int16_t  active_track = 1;          /* index of playing track */
static bool     liked = false;             /* heart icon liked state */

/* sheet animation */
static sgl_anim_t *sheet_anim;

/* static text buffer for time label (sgl_label_set_text stores pointer) */
static char g_time_buf[8];

/* track data */
static const char *track_name_list[TRACK_NUM] = {
    "Waiting for true love",
    "Need a Better Future",
    "Vibrations",
    "Why now?",
    "Midnight Sun",
    "Silver Rain",
    "Lost Echoes",
    "Neon Skyline",
    "Golden Hour",
    "Quiet Storm",
    "Aurora",
    "Starfall",
    "Night Drive",
    "Blue Horizon",
    "Crystal Lake",
    "Paper Planes",
    "Velvet Moon",
    "Amber Waves",
    "Zero Gravity",
    "Echo Valley",
};
static const char *track_artist_list[TRACK_NUM] = {
    "The John Smith Band",
    "My True Name",
    "Robotics",
    "Night Owl",
    "Luna Park",
    "Echo Valley",
    "Nova Beat",
    "Solar Twins",
    "Crystal Lake",
    "Paper Planes",
    "Velvet Moon",
    "Amber Waves",
    "Zero Gravity",
    "The Wanderers",
    "Luna Park",
    "Echo Valley",
    "Nova Beat",
    "Solar Twins",
    "Crystal Lake",
    "Paper Planes",
};
static const char *track_dur_list[TRACK_NUM] = {
    "1:14", "2:26", "1:54", "2:08", "3:15", "2:45", "1:58", "2:33",
    "3:02", "2:19", "1:47", "2:56", "3:28", "2:11", "1:39", "2:47",
    "3:09", "2:24", "1:52", "2:38",
};

static void fmt_time(char *buf, uint32_t sec)
{
    sec = sec % 3600;
    snprintf(buf, 8, "%u:%02u", (unsigned)(sec / 60), (unsigned)(sec % 60));
}

static void progress_update(void)
{
    uint8_t pct = (uint8_t)(elapsed_sec * 100 / SONG_LEN_SEC);
    int16_t bar_w = sgl_obj_get_width(progress_bar);
    int16_t dot_x = (int16_t)(bar_w * pct / 100);

    fmt_time(g_time_buf, elapsed_sec);
    sgl_bar_set_value(progress_bar, pct);
    sgl_label_set_text(time_label, g_time_buf);

    /* move dot knob */
    sgl_obj_set_pos(progress_dot,
                    LEFT_X + dot_x - PROG_DOT / 2,
                    PROGRESS_Y + PROG_H / 2 - PROG_DOT / 2);
}

static void playing_set(bool play)
{
    playing = play;
    sgl_button_set_text(play_btn, play ? ICON_PAUSE : ICON_PLAY);
}

static void sheet_anim_path_cb(sgl_anim_t *anim, int32_t value)
{
    sheet_y = (int16_t)value;
    sgl_obj_set_pos(sheet, 0, sheet_y);
    sgl_obj_set_dirty(sheet);
}

static void sheet_anim_finish_cb(sgl_anim_t *anim)
{
    /* animation finished, update final state */
    sheet_y = sheet_open ? SHEET_Y_OPEN : SHEET_Y_CLOSE;
    sgl_obj_set_pos(sheet, 0, sheet_y);
    sgl_obj_set_dirty(sheet);
}

static void sheet_anim_start(bool open)
{
    if (sheet_anim == NULL) {
        sheet_anim = sgl_anim_create();
        if (sheet_anim == NULL) return;
        sgl_anim_set_path(sheet_anim, sheet_anim_path_cb, SGL_ANIM_PATH_EASE_OUT);
        sgl_anim_set_finish_cb(sheet_anim, sheet_anim_finish_cb);
    }

    sgl_anim_stop(sheet_anim);
    sgl_anim_set_start_value(sheet_anim, sheet_y);
    sgl_anim_set_end_value(sheet_anim, open ? SHEET_Y_OPEN : SHEET_Y_CLOSE);
    sgl_anim_set_act_duration(sheet_anim, SHEET_ANIM_MS);
    sgl_anim_start(sheet_anim, SGL_ANIM_REPEAT_ONCE);
}

static void sheet_set_open(bool open)
{
    if (sheet_open == open) return;
    sheet_open = open;
    sheet_anim_start(open);
}

static void sheet_toggle(void)
{
    sheet_set_open(!sheet_open);
}

/* ------------------------------------------------------------------ */
/* viewlist callbacks                                                 */
/* ------------------------------------------------------------------ */

static void track_get_item(sgl_obj_t *list, int32_t index, sgl_viewlist_item_t *item)
{
    SGL_UNUSED(list);
    if (index < 0 || index >= TRACK_NUM) return;

    sgl_snprintf(item->text, sizeof(item->text), "%s", track_name_list[index]);
    sgl_snprintf(item->subtext, sizeof(item->subtext), "%s", track_artist_list[index]);
    item->icon = (index == active_track) ? ICON_PAUSE : ICON_PLAY;
}

static void track_draw_item(sgl_obj_t *list, sgl_surf_t *surf, sgl_area_t *clip,
                            sgl_area_t *coords, const sgl_viewlist_item_t *item, bool selected)
{
    SGL_UNUSED(list);
    const int16_t pad = 20;
    const int16_t btn_size = 34;
    const int16_t btn_x = coords->x1 + pad;
    const int16_t btn_y = coords->y1 + (coords->y2 - coords->y1 + 1 - btn_size) / 2;

    /* play/pause button circle */
    sgl_area_t btn_rect = {
        .x1 = btn_x, .y1 = btn_y,
        .x2 = btn_x + btn_size - 1, .y2 = btn_y + btn_size - 1,
    };
    sgl_color_t btn_color = selected ? COL_ACCENT : COL_SHEET_TOP;
    sgl_draw_fill_rect(surf, clip, &btn_rect, btn_size / 2, btn_color, 255);

    /* button icon */
    const char *icon = selected ? ICON_PAUSE : ICON_PLAY;
    const int16_t icon_w = (int16_t)sgl_font_get_string_width(icon, &sgl_icon_music20);
    const int16_t icon_h = (int16_t)sgl_font_get_height(&sgl_icon_music20);
    sgl_draw_string(surf, clip,
                    btn_x + (btn_size - icon_w) / 2,
                    btn_y + (btn_size - icon_h) / 2,
                    icon, selected ? SGL_COLOR_WHITE : COL_TRACK_BTN, 255, &sgl_icon_music20);

    /* track name */
    const int16_t text_x = btn_x + btn_size + 16;
    const int16_t name_y = coords->y1 + 10;
    sgl_draw_string(surf, clip, text_x, name_y, item->text,
                    selected ? COL_TRACK_ACT_N : COL_TRACK_NAME, 255, &consolas14);

    /* track artist */
    const int16_t artist_y = coords->y1 + 34;
    sgl_draw_string(surf, clip, text_x, artist_y, item->subtext,
                    selected ? COL_TRACK_ACT_A : COL_TRACK_ARTIST, 255, &consolas14);

    /* duration (right-aligned) */
    const char *dur = track_dur_list[item->index];
    const int16_t dur_w = (int16_t)sgl_font_get_string_width(dur, &consolas14);
    sgl_draw_string(surf, clip, coords->x2 - dur_w - pad,
                    coords->y1 + (coords->y2 - coords->y1 + 1 - sgl_font_get_height(&consolas14)) / 2,
                    dur, COL_TRACK_DUR, 255, &consolas14);
}

static void track_click_item(sgl_obj_t *list, int32_t index, const sgl_viewlist_item_t *item)
{
    SGL_UNUSED(list);
    SGL_UNUSED(item);
    if (index < 0 || index >= TRACK_NUM) return;

    active_track = index;
    elapsed_sec = 0;
    playing_set(true);
    progress_update();
    sgl_viewlist_refresh(track_viewlist);
}

/* ------------------------------------------------------------------ */
/* callbacks                                                          */
/* ------------------------------------------------------------------ */

static void tick_timer_cb(const sgl_timer_t *timer, void *user_data)
{
    SGL_UNUSED(timer);
    SGL_UNUSED(user_data);

    if (playing) {
        /* spectrum: sin envelope + random jitter, middle bars taller */
        spec_phase = (int16_t)((spec_phase + 1) % 360);
        for (int i = 0; i < SPEC_BARS; i++) {
            int16_t angle = (int16_t)(i * 180 / (SPEC_BARS - 1));
            int32_t env = sgl_sin(angle);   /* Q15: 0..32767 */
            uint16_t v = (uint16_t)(10 + (env * 40 >> 15) + rand() % 8);
            if (v > SPEC_H) v = SPEC_H;
            sgl_spectrum_set_bar_value(spectrum, i, v);
        }

        /* advance simulated playback: ~1 s per 1000 ms */
        elapsed_sec++;
        if (elapsed_sec >= SONG_LEN_SEC) {
            elapsed_sec = 0;
        }
        progress_update();
    }
}

static void play_click_cb(sgl_event_t *evt)
{
    if (evt->type == SGL_EVENT_CLICKED) {
        playing_set(!playing);
    }
}

static void prev_click_cb(sgl_event_t *evt)
{
    if (evt->type == SGL_EVENT_CLICKED) {
        elapsed_sec = 0;
        progress_update();
    }
}

static void next_click_cb(sgl_event_t *evt)
{
    if (evt->type == SGL_EVENT_CLICKED) {
        elapsed_sec = (elapsed_sec + 60) % SONG_LEN_SEC;
        progress_update();
    }
}

static void all_tracks_click_cb(sgl_event_t *evt)
{
    if (evt->type == SGL_EVENT_CLICKED) {
        sheet_toggle();
    }
}

/* sheet drag: detect swipe up/down on the main player area */
static void sheet_drag_cb(sgl_event_t *evt)
{
    switch (evt->type) {
    case SGL_EVENT_MOVE_UP:
        /* swipe up: open sheet */
        if (!sheet_open) {
            sheet_set_open(true);
        }
        break;

    case SGL_EVENT_MOVE_DOWN:
        /* swipe down: close sheet */
        if (sheet_open) {
            sheet_set_open(false);
        }
        break;

    default:
        break;
    }
}

/* ------------------------------------------------------------------ */
/* icon callbacks                                                     */
/* ------------------------------------------------------------------ */

/* heart icon: toggle liked state on click */
static void heart_click_cb(sgl_event_t *evt)
{
    if (evt->type == SGL_EVENT_CLICKED) {
        liked = !liked;
        sgl_label_set_text_color(evt->obj, liked ? sgl_rgb(255, 80, 100) : COL_ICON);
    }
}

/* generic icon: change color on press, restore on release */
static void icon_press_cb(sgl_event_t *evt)
{
    switch (evt->type) {
    case SGL_EVENT_PRESSED:
        sgl_label_set_text_color(evt->obj, COL_ACCENT);
        break;
    case SGL_EVENT_RELEASED:
        sgl_label_set_text_color(evt->obj, COL_ICON);
        break;
    default:
        break;
    }
}

/* ------------------------------------------------------------------ */
/* construction helpers                                               */
/* ------------------------------------------------------------------ */

static sgl_obj_t *icon_label_create(sgl_obj_t *parent, int16_t x, int16_t y,
                                    const char *icon, sgl_color_t color)
{
    sgl_obj_t *obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, x, y);
    sgl_obj_set_size(obj, 32, 32);
    sgl_label_set_font(obj, &sgl_icon_music20);
    sgl_label_set_text(obj, icon);
    sgl_label_set_text_color(obj, color);
    sgl_label_set_text_align(obj, SGL_ALIGN_CENTER);
    return obj;
}

/* clickable icon with press/release color change */
static sgl_obj_t *icon_clickable_create(sgl_obj_t *parent, int16_t x, int16_t y,
                                        const char *icon, sgl_color_t color,
                                        void (*cb)(sgl_event_t *))
{
    sgl_obj_t *obj = icon_label_create(parent, x, y, icon, color);
    sgl_obj_set_clickable(obj);
    sgl_obj_set_event_cb(obj, cb, NULL);
    return obj;
}

/* control button: change color on press, restore on release */
static void ctrl_btn_press_cb(sgl_event_t *evt)
{
    sgl_obj_t *btn = evt->obj;
    bool is_accent = (btn == play_btn);

    switch (evt->type) {
    case SGL_EVENT_PRESSED:
        sgl_button_set_color(btn, is_accent ? COL_ACCENT_LIGHT : COL_TRACK);
        break;
    case SGL_EVENT_RELEASED:
        sgl_button_set_color(btn, is_accent ? COL_ACCENT : COL_BG);
        break;
    default:
        break;
    }
}

/* control button callbacks */
static void shuffle_btn_cb(sgl_event_t *evt)
{
    ctrl_btn_press_cb(evt);
    /* TODO: shuffle mode toggle */
}

static void prev_btn_cb(sgl_event_t *evt)
{
    ctrl_btn_press_cb(evt);
    if (evt->type == SGL_EVENT_CLICKED) {
        prev_click_cb(evt);
    }
}

static void play_btn_cb(sgl_event_t *evt)
{
    ctrl_btn_press_cb(evt);
    if (evt->type == SGL_EVENT_CLICKED) {
        play_click_cb(evt);
    }
}

static void next_btn_cb(sgl_event_t *evt)
{
    ctrl_btn_press_cb(evt);
    if (evt->type == SGL_EVENT_CLICKED) {
        next_click_cb(evt);
    }
}

static void repeat_btn_cb(sgl_event_t *evt)
{
    ctrl_btn_press_cb(evt);
    /* TODO: repeat mode toggle */
}

static sgl_obj_t *ctrl_button_create(sgl_obj_t *parent, int16_t x, int16_t y,
                                     int16_t w, int16_t h, const char *icon,
                                     bool accent, void (*cb)(sgl_event_t *))
{
    sgl_obj_t *btn = sgl_button_create(parent);
    sgl_obj_set_pos(btn, x, y);
    sgl_obj_set_size(btn, w, h);
    sgl_obj_set_radius(btn, h / 2);
    sgl_obj_set_border_width(btn, 0);
    sgl_button_set_color(btn, accent ? COL_ACCENT : COL_BG);
    sgl_button_set_text_color(btn, accent ? sgl_rgb(255, 255, 255) : COL_ICON_CTRL);
    sgl_button_set_font(btn, &sgl_icon_music20);
    sgl_button_set_text(btn, icon);
    sgl_obj_set_clickable(btn);
    sgl_obj_set_event_cb(btn, cb, NULL);
    return btn;
}

/* ------------------------------------------------------------------ */
/* public entry                                                       */
/* ------------------------------------------------------------------ */

void sgl_demo_music_player_create(sgl_obj_t *parent)
{
    sgl_obj_t *obj;
    sgl_timer_t *tick;
    int16_t x, y;

    /* initialize sheet position */
    sheet_y = SHEET_Y_CLOSE;

    /* full screen background */
    obj = sgl_rect_create(parent);
    sgl_obj_set_pos(obj, 0, 0);
    sgl_obj_set_size(obj, SCR_W, SCR_H);
    sgl_rect_set_color(obj, COL_BG);
    sgl_obj_set_border_width(obj, 0);
    sgl_obj_set_movable(obj);  /* enable MOVE_UP/MOVE_DOWN events */
    sgl_obj_set_event_cb(obj, sheet_drag_cb, NULL);

    /* ------- decorative blobs (alpha-blended circles) ------- */
    obj = sgl_circle_create(parent);
    sgl_obj_set_pos(obj, -SCR_W / 6, -SCR_H / 3);
    sgl_obj_set_size(obj, SCR_W / 2, SCR_W / 2);
    sgl_circle_set_color(obj, COL_BLOB1);
    sgl_circle_set_alpha(obj, 140);
    sgl_obj_set_border_width(obj, 0);

    obj = sgl_circle_create(parent);
    sgl_obj_set_pos(obj, SCR_W - SCR_W / 3, SCR_H - SCR_H / 2);
    sgl_obj_set_size(obj, SCR_W / 2, SCR_W / 2);
    sgl_circle_set_color(obj, COL_BLOB2);
    sgl_circle_set_alpha(obj, 140);
    sgl_obj_set_border_width(obj, 0);

    obj = sgl_circle_create(parent);
    sgl_obj_set_pos(obj, SCR_W / 10, SCR_H - SCR_H / 3);
    sgl_obj_set_size(obj, SCR_W / 3, SCR_W / 3);
    sgl_circle_set_color(obj, COL_BLOB3);
    sgl_circle_set_alpha(obj, 140);
    sgl_obj_set_border_width(obj, 0);

    /* ------- left: title / artist / meta ------- */
    x = LEFT_X;
    y = TITLE_Y;

    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, x, y);
    sgl_obj_set_size(obj, LEFT_W, SCR_H / 13);
    sgl_label_set_font(obj, &consolas32);
    sgl_label_set_text(obj, "Need a Better Future");
    sgl_label_set_text_color(obj, COL_TITLE);
    sgl_label_set_text_align(obj, SGL_ALIGN_LEFT_MID);

    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, x, ARTIST_Y);
    sgl_obj_set_size(obj, LEFT_W, SCR_H / 18);
    sgl_label_set_font(obj, &consolas23);
    sgl_label_set_text(obj, "My True Name");
    sgl_label_set_text_color(obj, COL_ARTIST);
    sgl_label_set_text_align(obj, SGL_ALIGN_LEFT_MID);

    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, x, META_Y);
    sgl_obj_set_size(obj, LEFT_W, SCR_H / 22);
    sgl_label_set_font(obj, &consolas14);
    sgl_label_set_text(obj, "Drum'n bass - 2016");
    sgl_label_set_text_color(obj, COL_META);
    sgl_label_set_text_align(obj, SGL_ALIGN_LEFT_MID);

    /* ------- action icons row (heart, chart, download, more) ------- */
    y = ACTIONS_Y;
    icon_clickable_create(parent, x, y, ICON_HEART, COL_ICON, heart_click_cb);
    icon_clickable_create(parent, x + SCR_W / 13, y, ICON_CHART, COL_ICON, icon_press_cb);
    icon_clickable_create(parent, x + SCR_W / 6, y, ICON_DOWNLOAD, COL_ICON, icon_press_cb);
    icon_clickable_create(parent, x + SCR_W / 4, y, ICON_ELLIPSIS, COL_ICON, icon_press_cb);

    /* ------- control buttons row ------- */
    y = CONTROLS_Y;
    int16_t btn_spacing = SCR_W / 13;
    ctrl_button_create(parent, x, y + 14, 32, 32, ICON_SHUFFLE, false, shuffle_btn_cb);
    ctrl_button_create(parent, x + btn_spacing, y + 14, 32, 32, ICON_PREV, false, prev_btn_cb);
    play_btn = ctrl_button_create(parent, x + btn_spacing * 2, y + 8, 48, 48, ICON_PAUSE, true, play_btn_cb);
    ctrl_button_create(parent, x + btn_spacing * 3 + 20, y + 14, 32, 32, ICON_NEXT, false, next_btn_cb);
    ctrl_button_create(parent, x + btn_spacing * 4 + 20, y + 14, 32, 32, ICON_REPEAT, false, repeat_btn_cb);

    /* ------- progress bar + dot + time ------- */
    y = PROGRESS_Y;
    obj = sgl_bar_create(parent);
    sgl_obj_set_pos(obj, x, y);
    sgl_obj_set_size(obj, LEFT_W - SCR_W / 13, PROG_H);
    sgl_obj_set_radius(obj, PROG_H / 2);
    sgl_obj_set_border_width(obj, 0);
    sgl_bar_set_direct(obj, SGL_DIRECT_HORIZONTAL);
    sgl_bar_set_fill_color(obj, COL_ACCENT);
    sgl_bar_set_track_color(obj, COL_TRACK);
    sgl_bar_set_value(obj, 0);
    progress_bar = obj;

    progress_dot = sgl_circle_create(parent);
    sgl_obj_set_size(progress_dot, PROG_DOT, PROG_DOT);
    sgl_circle_set_color(progress_dot, COL_ACCENT);
    sgl_circle_set_border_color(progress_dot, sgl_rgb(255, 255, 255));
    sgl_circle_set_border_width(progress_dot, 2);
    sgl_obj_set_pos(progress_dot, x - PROG_DOT / 2, y + PROG_H / 2 - PROG_DOT / 2);

    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, x + LEFT_W - SCR_W / 16, y - 8);
    sgl_obj_set_size(obj, SCR_W / 16, 20);
    sgl_label_set_font(obj, &consolas14);
    sgl_label_set_text(obj, "0:00");
    sgl_label_set_text_color(obj, COL_META);
    sgl_label_set_text_align(obj, SGL_ALIGN_RIGHT_MID);
    time_label = obj;

    /* ------- right: circular cover ------- */
    x = RIGHT_X + (RIGHT_W - COVER_SIZE) / 2;
    y = MARGIN_TOP + 20;

    obj = sgl_circle_create(parent);
    sgl_obj_set_pos(obj, x, y);
    sgl_obj_set_size(obj, COVER_SIZE, COVER_SIZE);
    sgl_circle_set_color(obj, COL_COVER_DARK);
    sgl_circle_set_border_color(obj, sgl_rgb(255, 255, 255));
    sgl_circle_set_border_width(obj, 6);
    sgl_obj_set_clickable(obj);
    sgl_obj_set_event_cb(obj, play_click_cb, NULL);

    /* music note icon on cover */
    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, x, y);
    sgl_obj_set_size(obj, COVER_SIZE, COVER_SIZE);
    sgl_label_set_font(obj, &sgl_icon_music20);
    sgl_label_set_text(obj, ICON_MUSIC);
    sgl_label_set_text_color(obj, sgl_rgb(255, 255, 255));
    sgl_label_set_text_align(obj, SGL_ALIGN_CENTER);

    /* ------- spectrum below cover ------- */
    y += COVER_SIZE + SCR_H / 20;
    spectrum = sgl_spectrum_create(parent);
    sgl_obj_set_pos(spectrum, RIGHT_X + (RIGHT_W - SPEC_W) / 2, y);
    sgl_obj_set_size(spectrum, SPEC_W, SPEC_H);
    sgl_spectrum_set_bar_number(spectrum, SPEC_BARS);
    sgl_spectrum_set_bar_mode(spectrum, SGL_SPECTRUM_MODE_BAR);
    sgl_spectrum_set_bar_color(spectrum, COL_SPEC_BOT);
    sgl_spectrum_set_alpha(spectrum, 255);

    /* ------- bottom: ALL TRACKS (click to toggle sheet) ------- */
    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, 0, SCR_H - SCR_H / 16);
    sgl_obj_set_size(obj, SCR_W, SCR_H / 30);
    sgl_label_set_font(obj, &consolas14);
    sgl_label_set_text(obj, "ALL TRACKS");
    sgl_label_set_text_color(obj, COL_ALLTRACKS);
    sgl_label_set_text_align(obj, SGL_ALIGN_CENTER);
    sgl_obj_set_clickable(obj);
    sgl_obj_set_event_cb(obj, all_tracks_click_cb, NULL);

    /* small underline decoration */
    obj = sgl_rect_create(parent);
    sgl_obj_set_pos(obj, SCR_W / 2 - 15, SCR_H - 8);
    sgl_obj_set_size(obj, 30, 2);
    sgl_obj_set_radius(obj, 1);
    sgl_obj_set_border_width(obj, 0);
    sgl_rect_set_color(obj, COL_ALLTRACKS_LN);

    /* ------- sheet (track list panel, initially hidden below screen) ------- */
    sheet = sgl_rect_create(parent);
    sgl_obj_set_pos(sheet, 0, SHEET_Y_CLOSE);
    sgl_obj_set_size(sheet, SCR_W, SHEET_H);
    sgl_obj_set_radius(sheet, SHEET_RADIUS);
    sgl_obj_set_border_width(sheet, 0);
    sgl_rect_set_color(sheet, COL_SHEET_TOP);
    sgl_obj_set_movable(sheet);  /* enable MOVE_UP/MOVE_DOWN events */
    sgl_obj_set_event_cb(sheet, sheet_drag_cb, NULL);

    /* sheet handle */
    sheet_handle = sgl_rect_create(sheet);
    sgl_obj_set_pos(sheet_handle, (SCR_W - SHEET_HANDLE_W) / 2, 10);
    sgl_obj_set_size(sheet_handle, SHEET_HANDLE_W, SHEET_HANDLE_H);
    sgl_obj_set_radius(sheet_handle, SHEET_HANDLE_H / 2);
    sgl_obj_set_border_width(sheet_handle, 0);
    sgl_rect_set_color(sheet_handle, COL_HANDLE);
    sgl_rect_set_alpha(sheet_handle, 70);

    /* track list using viewlist widget */
    track_viewlist = sgl_viewlist_create(sheet);
    sgl_obj_set_pos(track_viewlist, 0, 24);
    sgl_obj_set_size(track_viewlist, SCR_W, SHEET_H - 24);
    sgl_viewlist_set_bg_color(track_viewlist, COL_SHEET_TOP);
    sgl_viewlist_set_border_width(track_viewlist, 0);
    sgl_viewlist_set_radius(track_viewlist, 0);
    sgl_viewlist_set_item_height(track_viewlist, TRACK_ITEM_H);
    sgl_viewlist_set_item_margin(track_viewlist, 0, 0);
    sgl_viewlist_set_font(track_viewlist, &consolas14);
    sgl_viewlist_set_text_color(track_viewlist, COL_TRACK_NAME);
    sgl_viewlist_set_subtext_color(track_viewlist, COL_TRACK_ARTIST);
    sgl_viewlist_set_selected_color(track_viewlist, COL_SHEET_BOT);
    sgl_viewlist_set_alpha(track_viewlist, 255);

    /* set viewlist callbacks */
    sgl_viewlist_set_item_num(track_viewlist, TRACK_NUM);
    sgl_viewlist_set_item_get_cb(track_viewlist, track_get_item);
    sgl_viewlist_set_item_draw_cb(track_viewlist, track_draw_item);
    sgl_viewlist_set_item_click_cb(track_viewlist, track_click_item);
    sgl_viewlist_set_selected(track_viewlist, active_track);

    /* ------- animation timer (30 FPS UI) ------- */
    tick = sgl_timer_create();
    sgl_timer_setup(tick, tick_timer_cb, 30, -1, NULL);
}
