/* demos/music/music_player.c
 *
 * MIT License
 *
 * Copyright(c) 2023-present All contributors of SGL
 * Document reference link: https://sgl-docs.readthedocs.io
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <sgl.h>
#include <sgl_font.h>
#include <stdio.h>
#include <stdlib.h>

/**
 * Music player UI demo (light theme, full screen 800x480).
 *
 * Layout follows demos/music/layout.html, scaled up to fill the screen:
 *   - background: #eef0f6 full screen
 *   - 3 decorative background blobs (light circles, alpha-blended)
 *   - left column: title / artist / meta, 4 action icons, 5 control buttons,
 *     progress bar with dot knob + time label
 *   - right column: 250px circular cover with white border + music icon,
 *     46-bar spectrum below
 *   - bottom center: "ALL TRACKS" caption with small underline
 *
 * Icons are FontAwesome glyphs converted to sgl/source/fonts/sgl_icon_music20.c
 * via sgl_font_conv_cli (20px, bpp=4).
 */

/* generated by sgl_font_conv_cli from fonts/FontAwesome.otf */
extern const sgl_font_t sgl_icon_music20;

/* FontAwesome icon codepoints (UTF-8 encoded) */
#define ICON_MUSIC       "\xf0\x8f\x80\x81"   /* U+F001 music           */
#define ICON_HEART       "\xf0\x8f\x80\x84"   /* U+F004 heart           */
#define ICON_DOWNLOAD    "\xf0\x8f\x80\x99"   /* U+F019 download        */
#define ICON_REPEAT      "\xf0\x8f\x80\x9e"   /* U+F01E repeat          */
#define ICON_PREV        "\xef\x81\x88"       /* U+F048 backward-step   */
#define ICON_PLAY        "\xef\x81\x8b"       /* U+F04B play            */
#define ICON_PAUSE       "\xef\x81\x8c"       /* U+F04C pause           */
#define ICON_NEXT        "\xef\x81\x91"       /* U+F051 forward-step    */
#define ICON_SHUFFLE     "\xef\x81\xb4"       /* U+F074 shuffle         */
#define ICON_CHART       "\xef\x82\x80"       /* U+F080 chart-bar       */
#define ICON_ELLIPSIS    "\xef\x85\x81"       /* U+F141 ellipsis-h      */

/* screen geometry */
#define SCR_W            800
#define SCR_H            480

/* layout margins */
#define MARGIN_X         60
#define MARGIN_TOP       50
#define MARGIN_BOT       50

/* left column */
#define LEFT_X           MARGIN_X
#define LEFT_W           400
#define TITLE_Y          MARGIN_TOP
#define ARTIST_Y         (TITLE_Y + 40)
#define META_Y           (ARTIST_Y + 28)
#define ACTIONS_Y        (META_Y + 50)
#define CONTROLS_Y       (ACTIONS_Y + 60)
#define PROGRESS_Y       (SCR_H - MARGIN_BOT - 20)

/* right column */
#define RIGHT_X          (SCR_W - MARGIN_X - 280)
#define RIGHT_W          280
#define COVER_SIZE       250
#define SPEC_W           280
#define SPEC_H           60
#define SPEC_BARS        46

/* progress */
#define PROG_H           6
#define PROG_DOT         12
#define SONG_LEN_SEC     214   /* 3:34 */

/* color palette (light theme, from layout.html) */
#define COL_BG           sgl_rgb(238, 240, 246)   /* #eef0f6 */
#define COL_TITLE        sgl_rgb(59, 63, 82)      /* #3b3f52 */
#define COL_ARTIST       sgl_rgb(74, 78, 99)      /* #4a4e63 */
#define COL_META         sgl_rgb(138, 143, 165)   /* #8a8fa5 */
#define COL_ICON         sgl_rgb(91, 96, 118)     /* #5b6076 */
#define COL_ICON_CTRL    sgl_rgb(106, 111, 134)   /* #6a6f86 */
#define COL_ACCENT       sgl_rgb(122, 104, 245)   /* #7a68f5 */
#define COL_ACCENT_LIGHT sgl_rgb(157, 141, 255)   /* #9d8dff */
#define COL_TRACK        sgl_rgb(226, 228, 238)   /* #e2e4ee */
#define COL_BLOB1        sgl_rgb(223, 228, 255)   /* #dfe4ff */
#define COL_BLOB2        sgl_rgb(230, 233, 251)   /* #e6e9fb */
#define COL_BLOB3        sgl_rgb(215, 240, 238)   /* #d7f0ee */
#define COL_COVER_DARK   sgl_rgb(35, 32, 58)      /* #23203a */
#define COL_SPEC_BOT     sgl_rgb(138, 123, 248)   /* #8a7bf8 */
#define COL_ALLTRACKS    sgl_rgb(125, 129, 160)   /* #7d81a0 */
#define COL_ALLTRACKS_LN sgl_rgb(201, 196, 245)   /* #c9c4f5 */

/* widgets */
static sgl_obj_t *progress_bar;
static sgl_obj_t *progress_dot;
static sgl_obj_t *time_label;
static sgl_obj_t *play_btn;
static sgl_obj_t *spectrum;

/* player state */
static bool     playing = true;
static uint32_t elapsed_sec;
static int16_t  spec_phase;

/* static text buffer for time label (sgl_label_set_text stores pointer) */
static char g_time_buf[8];

/* ------------------------------------------------------------------ */
/* helpers                                                            */
/* ------------------------------------------------------------------ */

static void fmt_time(char *buf, uint32_t sec)
{
    sec = sec % 3600;
    snprintf(buf, 8, "%u:%02u", (unsigned)(sec / 60), (unsigned)(sec % 60));
}

static void progress_update(void)
{
    uint8_t pct = (uint8_t)(elapsed_sec * 100 / SONG_LEN_SEC);
    int16_t bar_w = sgl_obj_get_width(progress_bar);
    int16_t dot_x = (int16_t)(bar_w * pct / 100);

    fmt_time(g_time_buf, elapsed_sec);
    sgl_bar_set_value(progress_bar, pct);
    sgl_label_set_text(time_label, g_time_buf);

    /* move dot knob */
    sgl_obj_set_pos(progress_dot,
                    LEFT_X + dot_x - PROG_DOT / 2,
                    PROGRESS_Y + PROG_H / 2 - PROG_DOT / 2);
}

static void playing_set(bool play)
{
    playing = play;
    sgl_button_set_text(play_btn, play ? ICON_PAUSE : ICON_PLAY);
}

/* ------------------------------------------------------------------ */
/* callbacks                                                          */
/* ------------------------------------------------------------------ */

static void tick_timer_cb(const sgl_timer_t *timer, void *user_data)
{
    SGL_UNUSED(timer);
    SGL_UNUSED(user_data);

    if (playing) {
        /* spectrum: sin envelope + random jitter, middle bars taller */
        spec_phase = (int16_t)((spec_phase + 1) % 360);
        for (int i = 0; i < SPEC_BARS; i++) {
            int16_t angle = (int16_t)(i * 180 / (SPEC_BARS - 1));
            int32_t env = sgl_sin(angle);   /* Q15: 0..32767 */
            uint16_t v = (uint16_t)(10 + (env * 40 >> 15) + rand() % 8);
            if (v > SPEC_H) v = SPEC_H;
            sgl_spectrum_set_bar_value(spectrum, i, v);
        }

        /* advance simulated playback: ~1 s per 1000 ms */
        elapsed_sec++;
        if (elapsed_sec >= SONG_LEN_SEC) {
            elapsed_sec = 0;
        }
        progress_update();
    }
}

static void play_click_cb(sgl_event_t *evt)
{
    if (evt->type == SGL_EVENT_CLICKED) {
        playing_set(!playing);
    }
}

static void prev_click_cb(sgl_event_t *evt)
{
    if (evt->type == SGL_EVENT_CLICKED) {
        elapsed_sec = 0;
        progress_update();
    }
}

static void next_click_cb(sgl_event_t *evt)
{
    if (evt->type == SGL_EVENT_CLICKED) {
        elapsed_sec = (elapsed_sec + 60) % SONG_LEN_SEC;
        progress_update();
    }
}

/* ------------------------------------------------------------------ */
/* construction helpers                                               */
/* ------------------------------------------------------------------ */

static sgl_obj_t *icon_label_create(sgl_obj_t *parent, int16_t x, int16_t y,
                                    const char *icon, sgl_color_t color)
{
    sgl_obj_t *obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, x, y);
    sgl_obj_set_size(obj, 32, 32);
    sgl_label_set_font(obj, &sgl_icon_music20);
    sgl_label_set_text(obj, icon);
    sgl_label_set_text_color(obj, color);
    sgl_label_set_text_align(obj, SGL_ALIGN_CENTER);
    return obj;
}

static sgl_obj_t *ctrl_button_create(sgl_obj_t *parent, int16_t x, int16_t y,
                                     int16_t w, int16_t h, const char *icon,
                                     bool accent, void (*cb)(sgl_event_t *))
{
    sgl_obj_t *btn = sgl_button_create(parent);
    sgl_obj_set_pos(btn, x, y);
    sgl_obj_set_size(btn, w, h);
    sgl_obj_set_radius(btn, h / 2);
    sgl_obj_set_border_width(btn, 0);
    sgl_button_set_color(btn, accent ? COL_ACCENT : COL_BG);
    sgl_button_set_text_color(btn, accent ? sgl_rgb(255, 255, 255) : COL_ICON_CTRL);
    sgl_button_set_font(btn, &sgl_icon_music20);
    sgl_button_set_text(btn, icon);
    sgl_obj_set_clickable(btn);
    sgl_obj_set_event_cb(btn, cb, NULL);
    return btn;
}

/* ------------------------------------------------------------------ */
/* public entry                                                       */
/* ------------------------------------------------------------------ */

void sgl_demo_music_player_create(sgl_obj_t *parent)
{
    sgl_obj_t *obj;
    sgl_timer_t *tick;
    int16_t x, y;

    /* full screen background */
    obj = sgl_rect_create(parent);
    sgl_obj_set_pos(obj, 0, 0);
    sgl_obj_set_size(obj, SCR_W, SCR_H);
    sgl_rect_set_color(obj, COL_BG);
    sgl_obj_set_border_width(obj, 0);
    sgl_obj_set_clickable(obj);

    /* ------- decorative blobs (alpha-blended circles) ------- */
    obj = sgl_circle_create(parent);
    sgl_obj_set_pos(obj, -120, -160);
    sgl_obj_set_size(obj, 400, 400);
    sgl_circle_set_color(obj, COL_BLOB1);
    sgl_circle_set_alpha(obj, 140);
    sgl_obj_set_border_width(obj, 0);

    obj = sgl_circle_create(parent);
    sgl_obj_set_pos(obj, SCR_W - 280, SCR_H - 260);
    sgl_obj_set_size(obj, 420, 420);
    sgl_circle_set_color(obj, COL_BLOB2);
    sgl_circle_set_alpha(obj, 140);
    sgl_obj_set_border_width(obj, 0);

    obj = sgl_circle_create(parent);
    sgl_obj_set_pos(obj, 80, SCR_H - 180);
    sgl_obj_set_size(obj, 260, 260);
    sgl_circle_set_color(obj, COL_BLOB3);
    sgl_circle_set_alpha(obj, 140);
    sgl_obj_set_border_width(obj, 0);

    /* ------- left: title / artist / meta ------- */
    x = LEFT_X;
    y = TITLE_Y;

    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, x, y);
    sgl_obj_set_size(obj, LEFT_W, 36);
    sgl_label_set_font(obj, &consolas32);
    sgl_label_set_text(obj, "Need a Better Future");
    sgl_label_set_text_color(obj, COL_TITLE);
    sgl_label_set_text_align(obj, SGL_ALIGN_LEFT_MID);

    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, x, ARTIST_Y);
    sgl_obj_set_size(obj, LEFT_W, 26);
    sgl_label_set_font(obj, &consolas23);
    sgl_label_set_text(obj, "My True Name");
    sgl_label_set_text_color(obj, COL_ARTIST);
    sgl_label_set_text_align(obj, SGL_ALIGN_LEFT_MID);

    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, x, META_Y);
    sgl_obj_set_size(obj, LEFT_W, 22);
    sgl_label_set_font(obj, &consolas14);
    sgl_label_set_text(obj, "Drum'n bass - 2016");
    sgl_label_set_text_color(obj, COL_META);
    sgl_label_set_text_align(obj, SGL_ALIGN_LEFT_MID);

    /* ------- action icons row (heart, chart, download, more) ------- */
    y = ACTIONS_Y;
    icon_label_create(parent, x, y, ICON_HEART, COL_ICON);
    icon_label_create(parent, x + 60, y, ICON_CHART, COL_ICON);
    icon_label_create(parent, x + 120, y, ICON_DOWNLOAD, COL_ICON);
    icon_label_create(parent, x + 180, y, ICON_ELLIPSIS, COL_ICON);

    /* ------- control buttons row ------- */
    y = CONTROLS_Y;
    ctrl_button_create(parent, x, y + 14, 32, 32, ICON_SHUFFLE, false, NULL);
    ctrl_button_create(parent, x + 60, y + 14, 32, 32, ICON_PREV, false, prev_click_cb);
    play_btn = ctrl_button_create(parent, x + 120, y, 60, 60, ICON_PAUSE, true, play_click_cb);
    ctrl_button_create(parent, x + 200, y + 14, 32, 32, ICON_NEXT, false, next_click_cb);
    ctrl_button_create(parent, x + 260, y + 14, 32, 32, ICON_REPEAT, false, NULL);

    /* ------- progress bar + dot + time ------- */
    y = PROGRESS_Y;
    obj = sgl_bar_create(parent);
    sgl_obj_set_pos(obj, x, y);
    sgl_obj_set_size(obj, LEFT_W - 60, PROG_H);
    sgl_obj_set_radius(obj, PROG_H / 2);
    sgl_obj_set_border_width(obj, 0);
    sgl_bar_set_direct(obj, SGL_DIRECT_HORIZONTAL);
    sgl_bar_set_fill_color(obj, COL_ACCENT);
    sgl_bar_set_track_color(obj, COL_TRACK);
    sgl_bar_set_value(obj, 0);
    progress_bar = obj;

    progress_dot = sgl_circle_create(parent);
    sgl_obj_set_size(progress_dot, PROG_DOT, PROG_DOT);
    sgl_circle_set_color(progress_dot, COL_ACCENT);
    sgl_circle_set_border_color(progress_dot, sgl_rgb(255, 255, 255));
    sgl_circle_set_border_width(progress_dot, 2);
    sgl_obj_set_pos(progress_dot, x - PROG_DOT / 2, y + PROG_H / 2 - PROG_DOT / 2);

    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, x + LEFT_W - 50, y - 8);
    sgl_obj_set_size(obj, 50, 20);
    sgl_label_set_font(obj, &consolas14);
    sgl_label_set_text(obj, "0:00");
    sgl_label_set_text_color(obj, COL_META);
    sgl_label_set_text_align(obj, SGL_ALIGN_RIGHT_MID);
    time_label = obj;

    /* ------- right: circular cover ------- */
    x = RIGHT_X + (RIGHT_W - COVER_SIZE) / 2;
    y = MARGIN_TOP + 20;

    obj = sgl_circle_create(parent);
    sgl_obj_set_pos(obj, x, y);
    sgl_obj_set_size(obj, COVER_SIZE, COVER_SIZE);
    sgl_circle_set_color(obj, COL_COVER_DARK);
    sgl_circle_set_border_color(obj, sgl_rgb(255, 255, 255));
    sgl_circle_set_border_width(obj, 6);
    sgl_obj_set_clickable(obj);
    sgl_obj_set_event_cb(obj, play_click_cb, NULL);

    /* music note icon on cover */
    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, x, y);
    sgl_obj_set_size(obj, COVER_SIZE, COVER_SIZE);
    sgl_label_set_font(obj, &sgl_icon_music20);
    sgl_label_set_text(obj, ICON_MUSIC);
    sgl_label_set_text_color(obj, sgl_rgb(255, 255, 255));
    sgl_label_set_text_align(obj, SGL_ALIGN_CENTER);

    /* ------- spectrum below cover ------- */
    y += COVER_SIZE + 24;
    spectrum = sgl_spectrum_create(parent);
    sgl_obj_set_pos(spectrum, RIGHT_X + (RIGHT_W - SPEC_W) / 2, y);
    sgl_obj_set_size(spectrum, SPEC_W, SPEC_H);
    sgl_spectrum_set_bar_number(spectrum, SPEC_BARS);
    sgl_spectrum_set_bar_mode(spectrum, SGL_SPECTRUM_MODE_BAR);
    sgl_spectrum_set_bar_color(spectrum, COL_SPEC_BOT);
    sgl_spectrum_set_alpha(spectrum, 255);

    /* ------- bottom: ALL TRACKS ------- */
    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, 0, SCR_H - 30);
    sgl_obj_set_size(obj, SCR_W, 16);
    sgl_label_set_font(obj, &consolas14);
    sgl_label_set_text(obj, "ALL TRACKS");
    sgl_label_set_text_color(obj, COL_ALLTRACKS);
    sgl_label_set_text_align(obj, SGL_ALIGN_CENTER);

    /* small underline decoration */
    obj = sgl_rect_create(parent);
    sgl_obj_set_pos(obj, SCR_W / 2 - 15, SCR_H - 8);
    sgl_obj_set_size(obj, 30, 2);
    sgl_obj_set_radius(obj, 1);
    sgl_obj_set_border_width(obj, 0);
    sgl_rect_set_color(obj, COL_ALLTRACKS_LN);

    /* ------- animation timer (30 FPS UI) ------- */
    tick = sgl_timer_create();
    sgl_timer_setup(tick, tick_timer_cb, 10, -1, NULL);
}
