/* examples/img_ext.c
 *
 * MIT License
 *
 * Copyright(c) 2023-present All contributors of SGL
 * Document reference link: https://sgl-docs.readthedocs.io
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <sgl.h>

/**
 * img_ext (transformable image) example - rotation around the center.
 *
 * The source image is images/music.jpeg converted with sgl_image_conv_cli
 * (ARGB4444, no compression, resized to 200x200), see images/output/.
 *
 * Demonstrated:
 *   1. continuous rotation animated with sgl_timer, pivot defaults to
 *      the image center (no sgl_img_ext_set_pivot() call needed);
 *   2. the same image with an explicit center pivot rotated 45 degrees
 *      while scaled down 0.5x, staying centered on its position.
 */

/* generated by image_conv: const sgl_pixmap_t music_img_image */
extern const sgl_pixmap_t music_img_image;

#define IMG_W   200
#define IMG_H   200

/* the animated image */
static sgl_obj_t *spin_img;
static int16_t spin_angle;

/**
 * @brief timer callback: rotate the image by 2 degrees every tick
 * @param timer timer that expired
 * @param user_data user data (unused)
 * @return none
 */
static void spin_timer_cb(const sgl_timer_t *timer, void *user_data)
{
    SGL_UNUSED(timer);
    SGL_UNUSED(user_data);

    spin_angle = (spin_angle + 2) % 360;
    /* rotation happens around the image center by default */
    sgl_img_ext_set_rotation(spin_img, spin_angle);
}

/**
 * @brief create the img_ext rotation examples
 *
 * Screen is 800x480.
 *   image 1: centered at (240, 240), spins continuously around its center;
 *            the bounding box grows up to ~283x283 at 45deg, which fits.
 *   image 2: centered at (590, 240), static +45deg, scale 0.5x around the
 *            center pivot, bounding box stays ~142x142.
 *
 * @param parent parent object, NULL creates the images on the active screen
 * @return none
 */
void sgl_img_ext_examples(sgl_obj_t *parent)
{
    sgl_obj_t *img;
    sgl_timer_t *spin_timer;

    spin_img = sgl_img_ext_create(parent);
    sgl_img_ext_set_pixmap(spin_img, &music_img_image);
    sgl_obj_set_pos(spin_img, 0, 0);

    spin_timer = sgl_timer_create();
    sgl_timer_setup(spin_timer, spin_timer_cb, 10, -1, NULL); /* ~30 FPS */
}
