/* examples/music_player.c
 *
 * MIT License
 *
 * Copyright(c) 2023-present All contributors of SGL
 * Document reference link: https://sgl-docs.readthedocs.io
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <sgl.h>
#include <sgl_font.h>
#include <stdio.h>
#include <stdlib.h>

/**
 * Music player UI demo.
 *
 * A dark themed player screen (800x480):
 *   - left:  spinning vinyl disc (images/music_cropped.png converted to
 *            200x200 ARGB8565 as images/output/music_img.c), stops spinning
 *            when playback is paused;
 *   - right: song title / artist, a progress bar with time labels
 *            (mm:ss / mm:ss) that advances with playback, and playback
 *            control buttons using FontAwesome icon glyphs (converted to
 *            sgl/source/fonts/sgl_icon_player32.c via sgl_font_conv_cli);
 *   - bottom: an sgl_spectrum widget that dances while playing.
 *
 * Playback is simulated with timers (no audio backend), so the UI logic
 * (progress advance, pause / resume, disc spin stop) can be exercised.
 */

/* generated by image_conv from images/music_cropped.png */
extern const sgl_pixmap_t music_img_image;

/* generated by sgl_font_conv_cli from fonts/FontAwesome.otf */
extern const sgl_font_t sgl_icon_player32;

/* FontAwesome icon codepoints (UTF-8 encoded) */
#define ICON_MUSIC       "\xf0\x8f\x80\x81"   /* U+F001 music           */
#define ICON_PREV        "\xef\x81\x88"   /* U+F048 backward-step   */
#define ICON_PLAY        "\xef\x81\x8b"   /* U+F04B play            */
#define ICON_PAUSE       "\xef\x81\x8c"   /* U+F04C pause           */
#define ICON_NEXT        "\xef\x81\x91"   /* U+F051 forward-step    */

#define DISC_SIZE        200
#define DISC_POS_X       60                       /* left column       */
#define DISC_POS_Y       ((480 - DISC_SIZE) / 2)  /* vertically center */
#define PANEL_X          320                      /* right panel left  */
#define PANEL_W          440                      /* right panel width */
#define TITLE_Y          96
#define ARTIST_Y         160
#define BAR_Y            236
#define BAR_H            12
#define BTN_Y            296                      /* big play button   */
#define SPEC_Y           404
#define SPEC_H           56
#define SONG_LEN_SEC     214   /* 3:34 */
#define SPEC_BARS        20

/* color palette (dark theme) */
#define COL_BG           sgl_rgb(18, 18, 24)
#define COL_ACCENT       sgl_rgb(230, 60, 70)
#define COL_TEXT         sgl_rgb(235, 235, 240)
#define COL_SUBTEXT      sgl_rgb(150, 150, 160)
#define COL_TRACK        sgl_rgb(45, 45, 55)

/* widgets */
static sgl_obj_t *disc;
static sgl_obj_t *progress_bar;
static sgl_obj_t *time_cur_label;
static sgl_obj_t *time_total_label;
static sgl_obj_t *play_btn;
static sgl_obj_t *spectrum;

/* player state */
static bool     playing = true;
static uint32_t elapsed_sec;
static int16_t  disc_angle;

/* ------------------------------------------------------------------ */
/* helpers                                                            */
/* ------------------------------------------------------------------ */

static void fmt_time(char *buf, uint32_t sec)
{
    sec = sec % 3600;
    snprintf(buf, 8, "%02u:%02u", (unsigned)(sec / 60), (unsigned)(sec % 60));
}

/* sgl_label_set_text() only stores the pointer, so the buffer must outlive
 * the call: stack locals would dangle and the label would render garbage
 * (showing up as font 'unicode not found' warnings). Keep static buffers. */
static char g_time_cur_buf[8];
static char g_time_total_buf[8];

static void progress_update(void)
{
    fmt_time(g_time_cur_buf, elapsed_sec);
    sgl_bar_set_value(progress_bar, (uint8_t)(elapsed_sec * 100 / SONG_LEN_SEC));
    sgl_label_set_text(time_cur_label, g_time_cur_buf);
}

static void playing_set(bool play)
{
    playing = play;
    sgl_button_set_text(play_btn, play ? ICON_PAUSE : ICON_PLAY);
}

/* ------------------------------------------------------------------ */
/* callbacks                                                          */
/* ------------------------------------------------------------------ */

static void tick_timer_cb(const sgl_timer_t *timer, void *user_data)
{
    SGL_UNUSED(timer);
    SGL_UNUSED(user_data);

    /* spectrum dances with pseudo-random values while playing */
    if (playing) {
        for (int i = 0; i < SPEC_BARS; i++) {
            uint16_t v = (uint16_t)(20 + rand() % (sgl_obj_get_height(spectrum) - 24));
            sgl_spectrum_set_bar_value(spectrum, i, v);
        }

        /* advance simulated playback: ~1 s of song per 1000 ms of ticks */
        elapsed_sec++;
        if (elapsed_sec >= SONG_LEN_SEC) {
            elapsed_sec = 0;
        }
        progress_update();

        /* spin the disc */
        disc_angle = (int16_t)((disc_angle + 3) % 360);
        sgl_img_ext_set_rotation(disc, disc_angle);
    }
}

static void play_click_cb(sgl_event_t *evt)
{
    if (evt->type == SGL_EVENT_CLICKED) {
        playing_set(!playing);
    }
}

static void prev_click_cb(sgl_event_t *evt)
{
    if (evt->type == SGL_EVENT_CLICKED) {
        elapsed_sec = 0;
        progress_update();
    }
}

static void next_click_cb(sgl_event_t *evt)
{
    if (evt->type == SGL_EVENT_CLICKED) {
        elapsed_sec = (elapsed_sec + 60) % SONG_LEN_SEC;
        progress_update();
    }
}

static void disc_click_cb(sgl_event_t *evt)
{
    if (evt->type == SGL_EVENT_CLICKED) {
        playing_set(!playing);
    }
}

/* ------------------------------------------------------------------ */
/* construction helpers                                               */
/* ------------------------------------------------------------------ */

static sgl_obj_t *ctrl_button_create(sgl_obj_t *parent, int16_t x, int16_t y,
                                     int16_t w, int16_t h, const char *icon,
                                     bool accent, void (*cb)(sgl_event_t *))
{
    sgl_obj_t *btn = sgl_button_create(parent);
    sgl_obj_set_pos(btn, x, y);
    sgl_obj_set_size(btn, w, h);
    sgl_obj_set_radius(btn, h / 2);
    sgl_obj_set_border_width(btn, 0);
    sgl_button_set_color(btn, accent ? COL_ACCENT : COL_TRACK);
    sgl_button_set_text_color(btn, COL_TEXT);
    sgl_button_set_font(btn, &sgl_icon_player32);
    sgl_button_set_text(btn, icon);
    sgl_obj_set_clickable(btn);
    sgl_obj_set_event_cb(btn, cb, NULL);
    return btn;
}

/* ------------------------------------------------------------------ */
/* public entry                                                       */
/* ------------------------------------------------------------------ */

void sgl_music_player_create(sgl_obj_t *parent)
{
    sgl_obj_t *obj;
    sgl_timer_t *tick;
    int16_t bx;

    /* full screen background */
    obj = sgl_rect_create(parent);
    sgl_obj_set_pos(obj, 0, 0);
    sgl_obj_set_size(obj, 800, 480);
    sgl_rect_set_color(obj, COL_BG);
    sgl_obj_set_border_width(obj, 0);
    sgl_obj_set_clickable(obj);

    /* ------- left: spinning vinyl disc ------- */
    disc = sgl_img_ext_create(parent);
    sgl_img_ext_set_pixmap(disc, &music_img_image);
    sgl_obj_set_pos(disc, DISC_POS_X, DISC_POS_Y);
    sgl_obj_set_clickable(disc);
    sgl_obj_set_event_cb(disc, disc_click_cb, NULL);

    /* ------- right: song info with music icon ------- */
    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, PANEL_X, TITLE_Y);
    sgl_obj_set_size(obj, 44, 44);
    sgl_label_set_font(obj, &sgl_icon_player32);
    sgl_label_set_text(obj, ICON_MUSIC);
    sgl_label_set_text_color(obj, COL_ACCENT);

    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, PANEL_X + 48, TITLE_Y);
    sgl_obj_set_size(obj, PANEL_W - 48, 44);
    sgl_label_set_font(obj, &consolas32);
    sgl_label_set_text(obj, "Vinyl Dreams");
    sgl_label_set_text_color(obj, COL_TEXT);
    sgl_label_set_text_align(obj, SGL_ALIGN_LEFT_MID);

    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, PANEL_X, ARTIST_Y);
    sgl_obj_set_size(obj, PANEL_W, 30);
    sgl_label_set_font(obj, &consolas23);
    sgl_label_set_text(obj, "SGL Band - Analog Dreams");
    sgl_label_set_text_color(obj, COL_SUBTEXT);
    sgl_label_set_text_align(obj, SGL_ALIGN_LEFT_MID);

    /* ------- progress bar + time labels ------- */
    obj = sgl_bar_create(parent);
    sgl_obj_set_pos(obj, PANEL_X, BAR_Y);
    sgl_obj_set_size(obj, PANEL_W, BAR_H);
    sgl_obj_set_radius(obj, BAR_H / 2);
    sgl_obj_set_border_width(obj, 0);
    sgl_bar_set_direct(obj, SGL_DIRECT_HORIZONTAL);
    sgl_bar_set_fill_color(obj, COL_ACCENT);
    sgl_bar_set_track_color(obj, COL_TRACK);
    sgl_bar_set_value(obj, 0);
    progress_bar = obj;

    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, PANEL_X, BAR_Y + BAR_H + 8);
    sgl_obj_set_size(obj, 70, 24);
    sgl_label_set_font(obj, &consolas14);
    sgl_label_set_text(obj, "00:00");
    sgl_label_set_text_color(obj, COL_SUBTEXT);
    sgl_label_set_text_align(obj, SGL_ALIGN_LEFT_MID);
    time_cur_label = obj;

    fmt_time(g_time_total_buf, SONG_LEN_SEC);
    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, PANEL_X + PANEL_W - 70, BAR_Y + BAR_H + 8);
    sgl_obj_set_size(obj, 70, 24);
    sgl_label_set_font(obj, &consolas14);
    sgl_label_set_text(obj, g_time_total_buf);
    sgl_label_set_text_color(obj, COL_SUBTEXT);
    sgl_label_set_text_align(obj, SGL_ALIGN_RIGHT_MID);
    time_total_label = obj;

    /* ------- playback control buttons (FontAwesome icon glyphs) ------- */
    bx = PANEL_X + PANEL_W / 2;
    ctrl_button_create(parent, bx - 150, BTN_Y + 8, 80, 64, ICON_PREV, false, prev_click_cb);
    play_btn = ctrl_button_create(parent, bx - 45, BTN_Y, 90, 80, ICON_PAUSE, true, play_click_cb);
    ctrl_button_create(parent, bx + 70, BTN_Y + 8, 80, 64, ICON_NEXT, false, next_click_cb);

    /* ------- bottom spectrum (sgl_spectrum widget) ------- */
    spectrum = sgl_spectrum_create(parent);
    sgl_obj_set_pos(spectrum, PANEL_X, SPEC_Y);
    sgl_obj_set_size(spectrum, PANEL_W, SPEC_H);
    sgl_spectrum_set_bar_number(spectrum, SPEC_BARS);
    sgl_spectrum_set_bar_mode(spectrum, SGL_SPECTRUM_MODE_BAR_HAT);
    sgl_spectrum_set_bar_color(spectrum, COL_ACCENT);
    sgl_spectrum_set_bar_hat_color(spectrum, sgl_rgb(255, 130, 130));
    sgl_spectrum_set_alpha(spectrum, 255);

    /* ------- footer hint ------- */
    obj = sgl_label_create(parent);
    sgl_obj_set_pos(obj, DISC_POS_X, DISC_POS_Y + DISC_SIZE + 16);
    sgl_obj_set_size(obj, DISC_SIZE, 24);
    sgl_label_set_font(obj, &consolas14);
    sgl_label_set_text(obj, "click disc to pause");
    sgl_label_set_text_color(obj, COL_SUBTEXT);
    sgl_label_set_text_align(obj, SGL_ALIGN_CENTER);

    /* ------- animation timer (30 FPS UI) ------- */
    tick = sgl_timer_create();
    sgl_timer_setup(tick, tick_timer_cb, 33, -1, NULL);
}
